//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class logsInventoryAlert
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int itemId { get; set; }
        public int outletId { get; set; }
        public bool isVisible { get; set; }
        public bool isSeen { get; set; }
        public string messageComment { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual item item { get; set; }
        public virtual outlet outlet { get; set; }
        public virtual User User { get; set; }
    }
}
