//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class logsOutletStock
    {
        public int id { get; set; }
        public int itemId { get; set; }
        public decimal quantity { get; set; }
        public int outletId { get; set; }
        public int movementId { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> rate { get; set; }
    
        public virtual item item { get; set; }
        public virtual movementType movementType { get; set; }
        public virtual outlet outlet { get; set; }
    }
}
