//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class prItem
    {
        public int id { get; set; }
        public Nullable<int> itemid { get; set; }
        public decimal quantity { get; set; }
        public string comment { get; set; }
        public int prId { get; set; }
        public Nullable<decimal> rate { get; set; }
    
        public virtual item item { get; set; }
        public virtual prRequest prRequest { get; set; }
    }
}
